<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Raining Hearts</title>
    <style>
        body {
            margin: 0;
            overflow: hidden;
            background-color: #222;
        }
        .heart {
            position: absolute;
            color: red;
            font-size: 20px;
            user-select: none;
            animation: fall linear infinite;
        }
        @keyframes fall {
            0% {
                transform: translateY(-10vh);
                opacity: 1;
            }
            100% {
                transform: translateY(100vh);
                opacity: 0;
            }
        }
    </style>
</head>
<body>

<script>
    function createHeart() {
        const heart = document.createElement("div");
        heart.innerHTML = "❤️";
        heart.classList.add("heart");

        // Random position and animation duration
        heart.style.left = Math.random() * 100 + "vw";
        heart.style.animationDuration = Math.random() * 3 + 2 + "s"; // Between 2-5 seconds
        heart.style.fontSize = Math.random() * 20 + 10 + "px"; // Varying sizes

        document.body.appendChild(heart);

        // Remove heart after animation ends
        setTimeout(() => {
            heart.remove();
        }, 5000);
    }

    setInterval(createHeart, 200);
</script>

</body>
</html>
