<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Church Members List</title>
    <style>
        body { font-family: Arial, sans-serif; text-align: center; margin: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid black; padding: 8px; text-align: left; }
        th { background-color: #f4f4f4; }
        input, button { padding: 10px; margin: 5px; }
    </style>
</head>
<body>

    <h2>United Door of Faith Church - Members List</h2>

    <table>
        <thead>
            
        </thead>
        <tbody id="members-list"></tbody>
    </table>

    <h3>Add New Member</h3>
    <input type="text" id="name" placeholder="Name">
    <input type="number" id="age" placeholder="Age">
    <input type="text" id="contact" placeholder="Contact">
    <input type="text" id="address" placeholder="Address">
    <button onclick="addMember()">Add Member</button>

    <script>
        async function fetchMembers() {
            const response = await fetch('/members');
            const members = await response.json();
            const tableBody = document.getElementById('members-list');
            tableBody.innerHTML = '';

            members.forEach(member => {
                tableBody.innerHTML += `
                    <tr>
                        <td>${member.id}</td>
                        <td>${member.name}</td>
                        <td>${member.age}</td>
                        <td>${member.contact}</td>
                        <td>${member.address}</td>
                    </tr>`;
            });
        }

        async function addMember() {
            const name = document.getElementById('name').value;
            const age = document.getElementById('age').value;
            const contact = document.getElementById('contact').value;
            const address = document.getElementById('address').value;

            await fetch('/add_member', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ name, age, contact, address })
            });

            fetchMembers();
        }

        fetchMembers();
    </script>

</body>
</html>
